## Analizar alpha generado por la señal VIXSI en activos del SP500

In [1]:
#%pip install --upgrade investpy

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('seaborn-darkgrid')

import yfinance as yf
from bs4 import BeautifulSoup
import requests
from datetime import datetime
from datetime import timedelta
from dateutil.relativedelta import relativedelta
import time

In [2]:
tickers = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]
# Se seleccionan los activos que se unieron al índice antes del 2014
tickers = tickers[tickers["Date added"]<="2001-01-01"]
tickers = tickers.Symbol.to_list()
tickers.insert(0, 'SPY')

In [3]:
data = yf.download(tickers, '2008-01-01', '2024-08-25', auto_adjust=True)['Close']
# Print the first few rows of the fetched data
data.head()

[*********************100%***********************]  190 of 190 completed

1 Failed download:
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2008-01-01 -> 2024-08-25)')

,A,AAPL,ABT,ADBE,ADI,ADM,ADP,ADSK,AEE,AEP,...,VZ,WBA,WFC,WM,WMB,WMT,WY,XEL,XOM,YUM
Date,,,,,,,,,,,,,,,,,,,,,
2008-01-02 00:00:00,23.293409,5.876342,18.215656,41.709999,20.164036,29.735905,25.159904,48.240002,27.397554,23.718229,...,17.285099,22.745804,18.486851,20.450415,13.285969,10.909305,14.893607,12.195479,51.317230,19.597918
2008-01-03 00:00:00,23.062403,5.879056,18.104683,41.790001,19.858620,30.044687,24.973629,47.840000,27.377035,23.789951,...,17.365095,21.356928,18.118380,20.450415,13.627583,10.788347,15.035217,12.266995,51.492836,19.323713
2008-01-04 00:00:00,22.311625,5.430278,18.209135,40.360001,19.340736,30.123529,23.867567,45.700001,27.176746,23.713131,...,17.041079,20.887884,17.464035,19.683372,13.215418,10.634829,14.289702,12.129472,50.532440,19.049509
2008-01-07 00:00:00,22.677387,5.357592,18.767241,40.240002,19.095083,30.130087,24.385670,46.720001,27.531101,24.404680,...,17.341091,21.363016,17.584736,20.013012,13.148574,10.830217,14.187663,12.316501,50.060493,19.494450
2008-01-08 00:00:00,22.645296,5.164870,19.260099,39.220001,18.464331,29.578215,24.164454,44.820000,27.377035,24.389320,...,16.965342,20.851337,16.835094,20.114437,13.219131,10.692974,13.889874,12.189980,49.418415,18.997772

In [5]:
data = data.dropna(axis=1, how="all")
data.index = pd.to_datetime(data.index)
activos = data.columns

df_vixsi = pd.read_csv("../datos/VIXSIyf.csv", index_col=0)
df_vixsi.index =  pd.to_datetime(df_vixsi.index)
datos_vixsi = pd.concat([data[activos], df_vixsi.VIXSI], axis=1).dropna()

In [5]:
benchmark = data['SPY']
stock = data.drop(columns=['^SPY'])

stock_rets = stock.pct_change().dropna()
benchmark_rets = benchmark.pct_change().dropna()
    
corr = stock_rets.corrwith(benchmark_rets)
#corr = corr.sort_values(ascending=False)[0:30]
activos = corr.index.to_list()

df_vixsi = pd.read_csv("../datos/VIXSIyf.csv", index_col=0)
df_vixsi.index =  pd.to_datetime(df_vixsi.index)
datos_vixsi = pd.concat([stock[activos], df_vixsi.VIXSI], axis=1).dropna()

### alpha_vixsi_spy

Una forma de validar la señal es ver cuanto alpha genera la estrategia que utiliza la señal para invertir en largo (vixsi=1) o en corto (vixsi=-1) utilizando como benchmar el propio activo SPY.

la fórmula del alpha se basará en el alpha de Jensen (asignando 0 a la rentabilidad libre de riesgo):

rentabilidad estrategia - Beta_estrategia_benchmark * rentabilidad benchmark

El alpha se calculará por año, y se evaluará la media y el ratio de sharpe del alpha anual.

Los datos del SPY se recogerán de yfinance y se ajustarán a los dividendos.

In [11]:
def f_alpha(datos, estrategia="estrategia", benchmark="SPY"):
    '''

    '''

    srets = np.log(datos[estrategia]).diff().fillna(0)
    brets = np.log(datos[benchmark]).diff().fillna(0)

    #w_brets = brets.loc[srets.index]
    cov_rets = np.cov(srets.T, brets)[0,1:]
    var_brets = brets.var()
    beta = cov_rets / var_brets
    rent_srets = srets.sum()
    rent_brets = brets.sum()
    alpha = rent_srets - beta * rent_brets    
    return (alpha)


def f_alpha_activo (datos, activo):
    estrategia = "estr"+activo
    datos[estrategia] = (1 + datos.VIXSI.shift(1) * datos[activo].pct_change()).cumprod()
    años = sorted(datos.index.year.unique())
    alpha = np.zeros(len(años))
    for i in range(len(años)):
        alpha[i] = f_alpha(datos.loc[str(años[i])],estrategia=estrategia, benchmark=activo)

    alpha = pd.DataFrame(alpha, index=años)
    return (alpha, alpha.mean())

alpha_mean = np.zeros(len(activos))
for i,activo in enumerate(activos):
    alpha, _mean = f_alpha_activo (datos_vixsi, activo)
    alpha_mean[i] = _mean
    
alpha_mean = pd.DataFrame(alpha_mean, index=activos)

In [18]:
alpha_mean.columns = ["media"]

In [52]:
alpha_mean.loc["SPY"].values[0]

0.10964442626704665

In [58]:
print ("%activos media alpha>0:",
       (alpha_mean.media > 0).sum()/len(alpha_mean)*100, "%")
print ("%activos media alpha superior media alpha SPY:",
       (alpha_mean.media  > alpha_mean.loc["SPY"].values[0]).sum()/len(alpha_mean)*100, "%")

%activos media alpha>0: 94.70899470899471 %
%activos media alpha superior media alpha SPY: 46.03174603174603 %